/**
 * The panel-sized blue-noise threshold mask.
 *
 * Generated by scripts/generate-blue-noise.mjs -- run that to rebuild the PNG.
 *
 * It ships as a 16-bit greyscale PNG rather than an inlined array: at 1200x1600
 * the ranks are two million numbers, which has no business being JavaScript. It
 * is decoded by hand rather than through a canvas because a canvas would hand
 * back 8-bit channels and discard half the file.
 *
 * One panel-sized mask beats a small tiled one because a tile repeats its own
 * structure across the frame, and the eye picks that out as a grid long before
 * it notices the noise.
 */

import { decodeGreyscalePng, type GreyscaleImage } from "./png";
import blueNoiseUrl from "../dither/data/blue-noise-1200x1600.png?no-inline";

export const BLUE_NOISE_FILE = "blue-noise-1200x1600.png";

export type BlueNoiseSource = string | URL | ArrayBuffer | ArrayBufferView;

let texture: GreyscaleImage | null = null;
let loading: Promise<GreyscaleImage> | null = null;
let source: BlueNoiseSource | null = null;

/**
 * Point the loader at the PNG.
 *
 * Optional override for custom hosting or preloaded PNG bytes. Set it separately
 * in each worker that processes images; module caches are local to their realm.
 */
export function setBlueNoiseSource(next: BlueNoiseSource): void {
  source = next;
  texture = null;
  loading = null;
}

/** The mask, or null if it has not been loaded yet. */
export function getBlueNoiseTexture(): GreyscaleImage | null {
  return texture;
}

function resolveSource(): BlueNoiseSource {
  return source ?? blueNoiseUrl;
}

async function readBytes(from: BlueNoiseSource): Promise<Uint8Array> {
  if (from instanceof ArrayBuffer) return new Uint8Array(from);
  if (ArrayBuffer.isView(from)) {
    return new Uint8Array(from.buffer, from.byteOffset, from.byteLength);
  }
  const url = from instanceof URL ? from.href : from;
  if (url.startsWith("file:")) {
    // Node's fetch does not support file URLs. Keep this optional import out of
    // browser bundles; the file branch is only used by installed Node packages.
    const moduleName = "node:fs/promises";
    const { readFile } = await import(/* @vite-ignore */ moduleName);
    return new Uint8Array(await readFile(new URL(url)));
  }
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`blue noise: fetching ${BLUE_NOISE_FILE} failed with ${response.status}`);
  }
  return new Uint8Array(await response.arrayBuffer());
}

function canDecodeWithCanvas(): boolean {
  return (
    typeof createImageBitmap === "function" && typeof OffscreenCanvas === "function"
  );
}

/** The platform's own PNG decoder, which only ever hands back 8 bits per channel. */
async function decodeWithCanvas(bytes: Uint8Array): Promise<GreyscaleImage> {
  const bitmap = await createImageBitmap(new Blob([bytes]));
  const { width, height } = bitmap;
  const context = new OffscreenCanvas(width, height).getContext("2d");
  if (!context) throw new Error("blue noise: no 2d context to decode the PNG with");

  context.drawImage(bitmap, 0, 0);
  bitmap.close();
  const { data } = context.getImageData(0, 0, width, height);

  const samples = new Uint16Array(width * height);
  for (let i = 0; i < samples.length; i += 1) samples[i] = data[i * 4]!; // grey: any channel
  return { width, height, samples, maxValue: 255 };
}

async function decode(bytes: Uint8Array): Promise<GreyscaleImage> {
  try {
    return await decodeGreyscalePng(bytes);
  } catch (error) {
    // Keep the strict decoder's message where there is nothing to fall back to;
    // it says what is actually wrong with the file.
    if (!canDecodeWithCanvas()) throw error;
    console.warn(
      `blue noise: falling back to the platform PNG decoder, which reads ` +
        `${BLUE_NOISE_FILE} at 8-bit precision`,
      error
    );
    return decodeWithCanvas(bytes);
  }
}

/** Load and cache the mask. Concurrent callers share the one load. */
export function loadBlueNoiseTexture(): Promise<GreyscaleImage> {
  if (texture) return Promise.resolve(texture);
  if (!loading) {
    const pending = readBytes(resolveSource())
      .then(decode)
      .then((decoded) => {
        if (loading === pending) texture = decoded;
        return decoded;
      })
      .catch((error) => {
        if (loading === pending) loading = null;
        throw error;
      });
    loading = pending;
  }
  return loading;
}
